// Keep in sync with backend (llm.py)
// Order here matches dropdown order
export enum CodeGenerationModel {
  CLAUDE_OPUS_5_LOW = "claude-opus-5 (low effort)",
  CLAUDE_OPUS_5_MEDIUM = "claude-opus-5 (medium effort)",
  CLAUDE_OPUS_5_HIGH = "claude-opus-5 (high effort)",
  CLAUDE_OPUS_5_XHIGH = "claude-opus-5 (xhigh effort)",
  CLAUDE_OPUS_5_MAX = "claude-opus-5 (max effort)",
  CLAUDE_OPUS_4_8_LOW = "claude-opus-4-8 (low effort)",
  CLAUDE_OPUS_4_8_MEDIUM = "claude-opus-4-8 (medium effort)",
  CLAUDE_OPUS_4_8_HIGH = "claude-opus-4-8 (high effort)",
  CLAUDE_OPUS_4_8_XHIGH = "claude-opus-4-8 (xhigh effort)",
  CLAUDE_OPUS_4_8_MAX = "claude-opus-4-8 (max effort)",
  CLAUDE_FABLE_5_MAX = "claude-fable-5 (max effort)",
  CLAUDE_SONNET_4_6 = "claude-sonnet-4-6",
  GPT_5_5_NONE = "gpt-5.5 (no thinking)",
  GPT_5_5_LOW = "gpt-5.5 (low thinking)",
  GPT_5_5_MEDIUM = "gpt-5.5 (medium thinking)",
  GPT_5_5_HIGH = "gpt-5.5 (high thinking)",
  GPT_5_6_SOL_NONE = "gpt-5.6-sol (no thinking)",
  GPT_5_6_SOL_LOW = "gpt-5.6-sol (low thinking)",
  GPT_5_6_SOL_MEDIUM = "gpt-5.6-sol (medium thinking)",
  GPT_5_6_SOL_HIGH = "gpt-5.6-sol (high thinking)",
  GPT_5_6_SOL_XHIGH = "gpt-5.6-sol (xhigh thinking)",
  GPT_5_6_SOL_MAX = "gpt-5.6-sol (max thinking)",
  GPT_5_6_TERRA_LOW = "gpt-5.6-terra (low thinking)",
  GPT_5_5_XHIGH = "gpt-5.5 (xhigh thinking)",
  GPT_5_4_MINI_LOW = "gpt-5.4-mini (low thinking)",
  GEMINI_3_FLASH_PREVIEW_HIGH = "gemini-3-flash-preview (high thinking)",
  GEMINI_3_FLASH_PREVIEW_MINIMAL = "gemini-3-flash-preview (minimal thinking)",
  GEMINI_3_1_PRO_PREVIEW_HIGH = "gemini-3.1-pro-preview (high thinking)",
  GEMINI_3_1_PRO_PREVIEW_MEDIUM = "gemini-3.1-pro-preview (medium thinking)",
  GEMINI_3_1_PRO_PREVIEW_LOW = "gemini-3.1-pro-preview (low thinking)",
  GEMINI_3_5_FLASH_HIGH = "gemini-3.5-flash (high thinking)",
  GEMINI_3_5_FLASH_MEDIUM = "gemini-3.5-flash (medium thinking)",
  GEMINI_3_5_FLASH_LOW = "gemini-3.5-flash (low thinking)",
  GEMINI_3_5_FLASH_MINIMAL = "gemini-3.5-flash (minimal thinking)",
  GEMINI_3_6_FLASH_HIGH = "gemini-3.6-flash (high thinking)",
  GEMINI_3_6_FLASH_MEDIUM = "gemini-3.6-flash (medium thinking)",
  GEMINI_3_6_FLASH_LOW = "gemini-3.6-flash (low thinking)",
  GEMINI_3_6_FLASH_MINIMAL = "gemini-3.6-flash (minimal thinking)",
}
